# Generated by Django 4.2.24 on 2025-10-06 13:22

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0125_jobresult_date_started'),
        ('dcim', '0073_alter_powerport_power_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('commit_id', models.BigIntegerField(unique=True)),
                ('source', models.CharField(default='unknown', max_length=255)),
                ('event_type', models.CharField(default='unknown', max_length=50)),
                ('category', models.CharField(default='unknown', max_length=100)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('raw_message', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, default='info', max_length=100, null=True)),
                ('log_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.device')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['device', 'commit_id', 'source', 'event_type', 'message'],
            },
            bases=(nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
